SERVICE_NAME:="proxy-server"

.PHONY: build start restart stop clean

build:
	bash build.sh compile ${SERVICE_NAME}


start:
	bash build.sh start ${SERVICE_NAME}


restart:
	bash build.sh restart ${SERVICE_NAME}


stop:
	bash build.sh stop ${SERVICE_NAME}


clean:
	bash build.sh clean ${SERVICE_NAME}
